version: '3.8'
services:

  mysqldb:
    image: mysql:8.4.0
    environment:
      - MYSQL_DATABASE=bookstore
      - MYSQL_ROOT_PASSWORD=Welcome1
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local


